src/Entity/Tienda/CategoriaGrupo.php
<?php

namespace App\Entity\Tienda;

use App\Entity\Categoria;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Common\Common;

/**
 * @ORM\Entity(repositoryClass=App\Repository\Tienda\CategoriaGrupoRepository::class)
 */
class CategoriaGrupo extends Common {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

   /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categoria", inversedBy="categoriasGrupo")
     * @ORM\JoinColumn(name="categoria_id", referencedColumnName="id")     
     */
    protected $categoria;

   /**
     * @ORM\ManyToOne(targetEntity="Grupo", inversedBy="categoriasGrupo")
     * @ORM\JoinColumn(name="grupo_id", referencedColumnName="id")     
     */
    protected $grupo;

    public function getItem(){
        return $this->categoria;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoria(): ?Categoria
    {
        return $this->categoria;
    }

    public function setCategoria(?Categoria $categoria): self
    {
        $this->categoria = $categoria;

        return $this;
    }

    public function getGrupo(): ?Grupo
    {
        return $this->grupo;
    }

    public function setGrupo(?Grupo $grupo): self
    {
        $this->grupo = $grupo;

        return $this;
    }

}

src/Entity/Tienda/CategoriasubcategoriaGrupo.php
<?php

namespace App\Entity\Tienda;

use App\Entity\Categoria;
use App\Entity\Categoriasubcategoria;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Common\Common;

/**
 * @ORM\Entity(repositoryClass=App\Repository\Tienda\CategoriasubcategoriaGrupoRepository::class)
 */
class CategoriasubcategoriaGrupo extends Common {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categoriasubcategoria", inversedBy="categoriasubcategoriasGrupo")
     * @ORM\JoinColumn(name="subcategoria_id", referencedColumnName="id")     
     */
    protected $categoriasubcategoria;

    /**
     * @ORM\ManyToOne(targetEntity="Grupo", inversedBy="categoriasubcategoriasGrupo")
     * @ORM\JoinColumn(name="grupo_id", referencedColumnName="id")     
     */
    protected $grupo;

    public function getItem() {
        return $this->categoriasubcategoria;
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getGrupo(): ?Grupo {
        return $this->grupo;
    }

    public function setGrupo(?Grupo $grupo): self {
        $this->grupo = $grupo;

        return $this;
    }

    public function getCategoriasubcategoria(): ?Categoriasubcategoria
    {
        return $this->categoriasubcategoria;
    }

    public function setCategoriasubcategoria(?Categoriasubcategoria $categoriasubcategoria): self
    {
        $this->categoriasubcategoria = $categoriasubcategoria;

        return $this;
    }


}

src/Entity/Tienda/ClienteWeb.php
<?php

namespace App\Entity\Tienda;

use App\Repository\Tienda\ClienteWebRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Entity\Common\Common;

/**
 * @ORM\Entity(repositoryClass=App\Repository\Tienda\ClienteWebRepository::class)
 */
class ClienteWeb extends Common {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=100)
     *      @Assert\Length(
     *      max = 100,     
     *      maxMessage = "E-mail cannot exceed {{ limit }} characters"
     * )   
     */
    protected $email;

    /**
     * @ORM\Column(type="string", length=200)
     * @Assert\Length(
     *      max = 200,     
     *      maxMessage = "Name cannot exceed {{ limit }} characters"
     * )   
     */
    protected $nombre;
    
     /**
     * @ORM\Column(type="string", length=200, nullable=false)
     * @Assert\Length(
     *      max = 200,     
     *      maxMessage = "Surname cannot exceed {{ limit }} characters"
     * )   
     */
    protected $apellido;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Length(
     *      max = 100,     
     *      maxMessage = "Telephone number cannot exceed {{ limit }} characters"
     * )   
     */
    protected $telefono;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(
     *      max = 50,     
     *      maxMessage = "Dni cannot exceed {{ limit }} characters"
     * )   
     */
    protected $dni;

    /**
     * @ORM\OneToMany(targetEntity="Pedido", mappedBy="clienteWeb")
     */
    protected $pedidos;

    /**
     * @ORM\OneToMany(targetEntity="DireccionEnvio", mappedBy="clienteWeb")
     */
    protected $direccionesEnvio;

    /*     * ********************************
     * __construct
     *
     * 
     * ******************************** */

    public function __construct() {
        $this->pedidos = new ArrayCollection();
        $this->direccionesEnvio = new ArrayCollection();
    }

    /*     * ********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     * ******************************* */

    public function __toString() {
        return $this->getNombre();
    }

    public function getDireccion($tipoDireccion) {
        $direccionesEnvio = $this->getDireccionesEnvio();
        foreach ($direccionesEnvio as $direccionEnvio) {
            if ($direccionEnvio->getTipoDireccion()==$tipoDireccion){
                return $direccionEnvio;
            }            
        }
        return false;
    }
    /*
     * 
     */
    public function getTiposDireccion(){
        $tiposDireccion=[];
        foreach ($this->getDireccionesEnvio() as $direccionEnvio) {
            if ($direccionEnvio->getEnabled()){
                $tiposDireccion[]=$direccionEnvio->getTipoDireccion();
            }
        }
        return $tiposDireccion;        
    }   

    public function getId(): ?int {
        return $this->id;
    }

    public function getEmail(): ?string {
        return $this->email;
    }

    public function setEmail(string $email): self {
        $this->email = $email;

        return $this;
    }

    public function getNombre(): ?string {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self {
        $this->nombre = $nombre;

        return $this;
    }

    public function getTelefono(): ?string {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self {
        $this->telefono = $telefono;

        return $this;
    }

    public function getDni(): ?string {
        return $this->dni;
    }

    public function setDni(string $dni): self {
        $this->dni = $dni;

        return $this;
    }

    /**
     * @return Collection|Pedido[]
     */
    public function getPedidos(): Collection {
        return $this->pedidos;
    }

    public function addPedido(Pedido $pedido): self {
        if (!$this->pedidos->contains($pedido)) {
            $this->pedidos[] = $pedido;
            $pedido->setClienteWeb($this);
        }

        return $this;
    }

    public function removePedido(Pedido $pedido): self {
        if ($this->pedidos->contains($pedido)) {
            $this->pedidos->removeElement($pedido);
            // set the owning side to null (unless already changed)
            if ($pedido->getClienteWeb() === $this) {
                $pedido->setClienteWeb(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|DireccionEnvio[]
     */
    public function getDireccionesEnvio(): Collection {
        return $this->direccionesEnvio;
    }

    public function addDireccionesEnvio(DireccionEnvio $direccionesEnvio): self {
        if (!$this->direccionesEnvio->contains($direccionesEnvio)) {
            $this->direccionesEnvio[] = $direccionesEnvio;
            $direccionesEnvio->setClienteWeb($this);
        }

        return $this;
    }

    public function removeDireccionesEnvio(DireccionEnvio $direccionesEnvio): self {
        if ($this->direccionesEnvio->contains($direccionesEnvio)) {
            $this->direccionesEnvio->removeElement($direccionesEnvio);
            // set the owning side to null (unless already changed)
            if ($direccionesEnvio->getClienteWeb() === $this) {
                $direccionesEnvio->setClienteWeb(null);
            }
        }

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->apellido;
    }

    public function setApellido(string $apellido): self
    {
        $this->apellido = $apellido;

        return $this;
    }

}

src/Entity/Tienda/DetalleShipNowVerificacion.php
<?php

namespace App\Entity\Tienda;

use App\Repository\Tienda\DetalleShipNowVerificacionRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Recordatorio;
use App\Entity\Tienda\Pedido;

/**
 * @ORM\Entity(repositoryClass=App\Repository\Tienda\DetalleShipNowVerificacionRepository::class) 
 * @ORM\Table(name="detalleshipnowverificacion")
 */
class DetalleShipNowVerificacion {

    const ERROR = 'Error en el envío';
    const OK = 'Envío exitoso';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="ShipNowVerificacion", inversedBy="detallesShipNowVerificacion")
     * @ORM\JoinColumn(name="ship_now_verificacion_id", referencedColumnName="id")
     */
    private $shipNowVerificacion;

    /**
     * @ORM\ManyToOne(targetEntity="Pedido")
     * @ORM\JoinColumn(name="pedido_id", referencedColumnName="id", nullable=false)
     * */
    protected $pedido;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $resultado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getResultado(): ?string
    {
        return $this->resultado;
    }

    public function setResultado(?string $resultado): self
    {
        $this->resultado = $resultado;

        return $this;
    }

    public function getShipNowVerificacion(): ?ShipNowVerificacion
    {
        return $this->shipNowVerificacion;
    }

    public function setShipNowVerificacion(?ShipNowVerificacion $shipNowVerificacion): self
    {
        $this->shipNowVerificacion = $shipNowVerificacion;

        return $this;
    }

    public function getPedido(): ?Pedido
    {
        return $this->pedido;
    }

    public function setPedido(?Pedido $pedido): self
    {
        $this->pedido = $pedido;

        return $this;
    }


}

src/Entity/Tienda/Email.php
<?php

namespace App\Entity\Tienda;

use App\Repository\Tienda\EmailRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=App\Repository\Tienda\EmailRepository::class)
 */
class Email {

   
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=300)
     */
    protected $direccion;

     /**
     * @ORM\Column(type="boolean", nullable=false)
     */
   protected $activo = true;
    /*     * ********************************
     * __construct
     *
     * 
     * ******************************** */

    public function __construct() {
        
    }
    
     /*     * ********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     * ******************************* */

    public function __toString() {
        return $this->getDireccion();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): self
    {
        $this->direccion = $direccion;

        return $this;
    }

    public function getActivo(): ?bool
    {
        return $this->activo;
    }

    public function setActivo(bool $activo): self
    {
        $this->activo = $activo;

        return $this;
    }

   
}

src/Entity/Tienda/FormatoMail.php
<?php

namespace App\Entity\Tienda;

use Doctrine\ORM\Mapping as ORM;
use App\Entity\Common\Common;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=App\Repository\Tienda\FormatoMailRepository::class)
 * @UniqueEntity(
 *     fields={"type","configuracion"},
 *     errorPath="type",
 *     message="This configuration already has this mail format."
 * )
 */
class FormatoMail extends Common {

    const CONFIRM_USER = 'Confirm User';
    const CONFIRM_MINORISTA = 'Confirm Retail';
    const CONFIRM_CLIENTE_WEB = 'Confirm Web Client';
    const CONFIRM_MAYORISTA = 'Confirm Wholesaler';
    const CONFIRM_MAIL_RETAIL = 'Confirm Mail Retail';
    const CONFIRM_MAIL_WHOLESALER = 'Confirm Mail Wholesaler';
    const CONFIRM_PAYMENT_CLIENT = 'Confirm Payment Client';
    const CONFIRM_ORDER_TAKE_AWAY = 'Confirm Order Take away';
    const REMINDER_UNCONFIRMED_ORDER = 'Reminder Unconfirmed Order Payment';
    const COD_CONFIRM_USER = 1;
    const COD_CONFIRM_MINORISTA = 2;
    const COD_CONFIRM_CLIENTE_WEB = 3;
    const COD_CONFIRM_MAYORISTA = 4;
    const COD_CONFIRM_MAIL_RETAIL = 5;
    const COD_CONFIRM_PAYMENT_CLIENT = 6;
    const COD_CONFIRM_MAIL_WHOLESALER = 7;
    const COD_CONFIRM_ORDER_TAKE_AWAY = 8;
    const COD_REMINDER_UNCONFIRMED_ORDER = 9;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", options={"default" : 1})
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=4000)
     */
    private $title;

    /**
     * @ORM\Column(type="blob")
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=4000, nullable=true)
     */
    private $footer;

    /**
     * @ORM\ManyToOne(targetEntity="Configuracion", inversedBy="formatoMail")
     * @ORM\JoinColumn(name="configuracion_id", referencedColumnName="id")     
     */
    protected $configuracion;

    public function getTypeString() {
        switch ($this->getType()) {
            case self::COD_CONFIRM_USER:
                return self::CONFIRM_USER;
                
            case self::COD_CONFIRM_MINORISTA:
                return self::CONFIRM_MINORISTA;

            case self::COD_CONFIRM_CLIENTE_WEB:
                return self::CONFIRM_CLIENTE_WEB;

            case self::COD_CONFIRM_MAYORISTA:
                return self::CONFIRM_MAYORISTA;

            case self::COD_CONFIRM_MAIL_WHOLESALER:
                return self::CONFIRM_MAIL_WHOLESALER;
                
            case self::COD_CONFIRM_MAIL_RETAIL:
                return self::CONFIRM_MAIL_RETAIL;

            case self::COD_CONFIRM_PAYMENT_CLIENT:
                return self::CONFIRM_PAYMENT_CLIENT;
                
            case self::COD_CONFIRM_ORDER_TAKE_AWAY:
                return self::CONFIRM_ORDER_TAKE_AWAY;
                
            case self::COD_REMINDER_UNCONFIRMED_ORDER:
                return self::REMINDER_UNCONFIRMED_ORDER;    
        }
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getType(): ?string {
        return $this->type;
    }

    public function setType(string $type): self {
        $this->type = $type;

        return $this;
    }

    public function getTitle(): ?string {
        return $this->title;
    }

    public function setTitle(string $title): self {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string {
        if (is_resource($this->body)) {
            return stream_get_contents($this->body);
        } else {
            return $this->body;
        }
    }

    public function setBody(string $body): self {
        $this->body = $body;

        return $this;
    }

    public function getFooter(): ?string {
        return $this->footer;
    }

    public function setFooter(?string $footer): self {
        $this->footer = $footer;

        return $this;
    }

    public function getConfiguracion(): ?Configuracion {
        return $this->configuracion;
    }

    public function setConfiguracion(?Configuracion $configuracion): self {
        $this->configuracion = $configuracion;

        return $this;
    }

}

templates/tienda/formato_mail/_form.html.twig
{{ form_start(form) }}
<!-- /.card-header -->
<div class="card-body">  
    <div class="row">
        <div class="col-sm-6 mb-2">
            {{ form_row(form.type) }}                    
        </div>
        <div class="col-sm-6 mb-2">
            {{ form_row(form.configuracion) }}                    
        </div>
    </div>
    <div class="row">    
        <div class="col-sm-12 mb-2">
            {{ form_row(form.title) }}                    
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 mb-2">
            {{ form_row(form.body) }}                    
        </div>
    </div>
    <div class="row">    
        <div class="col-sm-12 mb-2">            
            {{ form_row(form.footer) }}            
        </div>
    </div>
    <br>    
    <button class="btn btn-info float-left mt-2 mb-2 mr-2" type="submit" >{{ 'Save'|trans }}</button>
</div>
<script>
    $('#formato_mail_title').summernote({
        toolbar: [
            // [groupName, [list of button]]
            ['style', ['style']],
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['color', ['color']],
        ],
        height: 100, // set editor height
        minHeight: null, // set minimum height of editor
        maxHeight: null, // set maximum height of editor
        focus: true, // set focus to editable area after initializing summernote
        lang: 'es-ES', // default: 'en-US'
        maximumImageFileSize: 614400
    });
    $('#formato_mail_body').summernote({
        toolbar: [
            // [groupName, [list of button]]
            ['style', ['style']],
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['color', ['color']],
        ],
        height: 300, // set editor height
        minHeight: null, // set minimum height of editor
        maxHeight: null, // set maximum height of editor
        focus: true, // set focus to editable area after initializing summernote
        lang: 'es-ES', // default: 'en-US'
        maximumImageFileSize: 614400
    });
    $('#formato_mail_footer').summernote({
        toolbar: [
            // [groupName, [list of button]]
            ['style', ['style']],
            ['style', ['bold', 'italic', 'underline', 'clear']],
            ['color', ['color']],
        ],
        height: 100, // set editor height
        minHeight: null, // set minimum height of editor
        maxHeight: null, // set maximum height of editor
        focus: true, // set focus to editable area after initializing summernote
        lang: 'es-ES', // default: 'en-US'
        maximumImageFileSize: 614400
    });
</script>
{{ form_end(form) }}

templates/tienda/formato_mail/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h4>{{'Mail Format'|trans}}</h4>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ path('tienda_formato_mail_index') }}" class="btn btn-sm btn-primary float-right">{{ "Go to list" | trans }}</a>
                    <a onclick="goBack();" class="btn btn-sm btn-info float-right" style="margin-right: 1rem;">{{ "Back" | trans }}</a>
                    <h5 >
                        <strong> {{ 'Edit mail format'|trans }}</strong>
                    </h5>
                </div>
                {{ include('tienda/formato_mail/_form.html.twig') }}   
            </div>
        </div>
    </div>
{% endblock %}

templates/tienda/formato_mail/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{% include('tienda/formato_mail/seeker.html.twig' ) %}
    <br>
    <div class="card shadow mb-4">
        <div class="card-header">           
            {% if is_granted('ROLE_ADMIN') %}             
            <a class="btn btn-sm btn-primary col-xs-3 float-right " href="{{ path('tienda_formato_mail_new') }}">{{'Create'|trans}}</a>
            {% endif %}
            <h6 class="font-weight-bold text-primary col-xs-3" >{{'Mail Format'|trans}}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">               
                <table  class="table table-bordered" data-toggle="table"  data-show-columns="true" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-sortable="true">{{ 'Id'|trans }} </th>
                            <th data-sortable="true">{{ 'Type'|trans }} </th>  
                            <th data-sortable="true">{{ 'Configuration'|trans }} </th>
                            <th data-sortable="true">{{ 'Status'|trans }} </th>
                            {% if is_granted('ROLE_ADMIN') %}                                        
                            <th>{{'Actions'|trans}}</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>
                        {% if formato_mails|length > 0 %}    
                            {% for formato_mail in formato_mails %}
                            <tr>
                                <td>{{ formato_mail.id }}</td>
                                <td>{{ formato_mail.typeString|trans }}</td>                               
                                <td><a href="{{ path('tienda_configuracion_show',{'id':formato_mail.configuracion.id}) }}">{{ formato_mail.configuracion }}</a></td>
                                <td>{{ formato_mail.enabledString|trans }}</td>
                                {% if is_granted('ROLE_ADMIN') %}                                        
                                <td>
                                    <a  class="mr-2" href="{{ path('tienda_formato_mail_show', {'id': formato_mail.id}) }}" title="{{ 'Edit'|trans }}">
                                        <i class="fas fa-eye text-success"></i>
                                    </a>
                                    <a  class="mr-2" href="{{ path('tienda_formato_mail_edit', {'id': formato_mail.id}) }}" title="{{ 'Edit'|trans }}">
                                        <i class="fas fa-edit text-primary"></i>
                                    </a>                                          
                                    {% if formato_mail.enabled %}                                        
                                        <a  href="{{ path('tienda_formato_mail_activate', { 'id': formato_mail.id,'activo': '0' }) }}"  title="{{ 'Inactivate'|trans }}" >
                                            <i class="fa fa-times text-danger mr-2"></i>
                                        </a>
                                    {% else %}                                    
                                        <a href="{{ path('tienda_formato_mail_activate', { 'id': formato_mail.id,'activo':'1' }) }}"  title="{{ 'Activate'|trans }}" >
                                            <i class="fa fa-undo text-warning"></i>
                                        </a>
                                    {% endif %}
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        {% else %}
                            <tr>                               
                                <th >{{'No records found'|trans}}</th>                                
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
                <div class="navigation">
                    {{ knp_pagination_render(formato_mails) }}
                </div>
            </div>
        </div>
    </div>     
{% endblock %}
{% block pagescripts %}
    <script type="text/javascript">

    </script>
{% endblock %}

templates/tienda/formato_mail/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h4>{{'Mail Format'|trans}}</h4>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ path('tienda_formato_mail_index') }}" class="btn btn-sm btn-primary float-right">{{ "Go to list" | trans }}</a>
                    <a onclick="goBack();" class="btn btn-sm btn-info float-right" style="margin-right: 1rem;">{{ "Back" | trans }}</a>
                    <h5 >
                        <strong> {{ 'New mail format'|trans }}</strong>
                    </h5>

                </div>
                {{ include('tienda/formato_mail/_form.html.twig') }}   
            </div>
        </div>
    </div>                
{% endblock %}

templates/tienda/formato_mail/seeker.html.twig
<div class="filters-content">
    <div class="card">
        <div class="card-header">
            <div class="btn-group btn-group-toggle col-xs-6 " data-toggle="buttons">
                <label class="btn btn-info btn-sm active showFilters " data-option="1">
                    <input  type="radio" name="options" id="option1" autocomplete="off" checked> {{ 'Hide filters' | trans }}
                </label>
                <label class="btn btn-info btn-sm showFilters"  data-option="2">
                    <input type="radio" name="options" id="option2" autocomplete="off">{{ 'Show filters' | trans }}
                </label>
            </div>
        </div>
        <div class="card-body" id="seekerFilters">
            <form class="col-xs-12" method="get" action="{{ path('tienda_formato_mail_index') }}"  >

                <div class="row">
                    <!--Filter by Type -->
                    <div class="col-sm-4">
                        <div class="form-group col-xs-12">
                            <label for="finder">
                                {{ 'Type' | trans }} 
                            </label>
                            <div class="input-group">  
                                {{ FormatoMailService.getSelectType() }}
                            </div>
                        </div>
                    </div>      
                    <div class="col-sm-4">
                        <div class="form-group col-xs-12">
                            <label for="estado">
                                {{ 'Status' | trans }} 
                            </label>
                            <div class="input-group">                                                                                             
                                {{ DefaultService.getStatusSelect() }}                                                       
                            </div>
                        </div>
                    </div>                   
                </div>
                <div class="row">
                    <a class="btn btn-success btn-sm ml-3" href="?reset">
                        <i class="fa fa-times"></i> {{ 'Clean' | trans | capitalize }}
                    </a>
                    <button class="btn btn-primary btn-sm" type="submit" style="margin-left:1rem;">
                        {{ 'Filter' | trans | capitalize }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>   
<script>
    $(function () {
        var activo = '{{ app.request.query.get('activo')}}';
        $('#activo').val(activo).change();
    });
</script>

templates/tienda/formato_mail/selectType.html.twig
<select id="type" name="type" class="form-control select2" >
    <option value="">{{ 'Select Type'|trans}}</option>
    {% for key,type in types %}
        <option value="{{type}}" >{{key|trans}}</option>          
    {% endfor %}
</select>

templates/tienda/formato_mail/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ 'Mail Preview'|trans}}
{% endblock %}

{% block body %}
    <h4>{{ 'Mail Preview'|trans}}</h4>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ path('tienda_formato_mail_index') }}" class="btn btn-sm btn-primary float-right">{{ "Go to list" | trans }}</a>
                    <a onclick="goBack();" class="btn btn-sm btn-info float-right" style="margin-right: 1rem;">{{ "Back" | trans }}</a>
                    <h5>
                        <strong> {{ 'View Mail Format'|trans }}</strong>
                    </h5>
                </div>              
                <div class="card-body">  
                    <div style="display:flex; flex-direction: row; justify-content: center; align-items: center">          
                        <img class="img-thumbnail" src="{{asset('tienda/img/' ~  imagen_src )}}" style="max-height: 50px;">&nbsp;&nbsp;&nbsp;{{formato_mail.title|raw}}
                    </div>
                    <br>
                    <br>
                    {{formato_mail.body|raw}}
                    <br>
                    <br>
                    <br>
                    {{formato_mail.footer|raw}}
                </div>                
            </div>
        </div>
    </div>   
{% endblock %}