src/Entity/TipoCheque.php
<?php

namespace App\Entity;

use App\TipoChequeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=App\Repository\TipoChequeRepository::class)
 * @ORM\Table(name="tipocheque")
  * @UniqueEntity(
 *     fields={"descripcion"},
 *     errorPath="descripcion",
 *     message="The check type already exists."
 * )
 */
class TipoCheque {

    const ACTIVO = 'ACTIVE';
    const NO_ACTIVO = 'INACTIVE';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string",length=300,nullable=false, unique=true)
     *      * @Assert\Length(
     *      max = 300,     
     *      maxMessage = "La descripción no puede superar los 300 caracteres"
     * )     
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    protected $activo = true;

    /**
     * @ORM\OneToMany(targetEntity="Cheque", mappedBy="tipoCheque")
     */
    protected $cheques;

    /*     * ********************************
     * __construct
     *
     * 
     * ******************************** */

    public function __construct() {
        $this->cheques = new ArrayCollection();
    }

    /*     * ********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     * ******************************* */

    public function __toString() {
        return $this->getDescripcion();
    }

    public function getActivoString() {
        if ($this->activo) {
            return self::ACTIVO;
        } else {
            return self::NO_ACTIVO;
        }
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getDescripcion(): ?string {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getActivo(): ?bool {
        return $this->activo;
    }

    public function setActivo(bool $activo): self {
        $this->activo = $activo;

        return $this;
    }

    /**
     * @return Collection|Cheque[]
     */
    public function getCheques(): Collection
    {
        return $this->cheques;
    }

    public function addCheque(Cheque $cheque): self
    {
        if (!$this->cheques->contains($cheque)) {
            $this->cheques[] = $cheque;
            $cheque->setTipoCheque($this);
        }

        return $this;
    }

    public function removeCheque(Cheque $cheque): self
    {
        if ($this->cheques->contains($cheque)) {
            $this->cheques->removeElement($cheque);
            // set the owning side to null (unless already changed)
            if ($cheque->getTipoCheque() === $this) {
                $cheque->setTipoCheque(null);
            }
        }

        return $this;
    }

}

src/Form/TipoChequeType.php
<?php

namespace App\Form;

use App\Entity\TipoCheque;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TipoChequeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
          -> add('descripcion', TextType::class, array('label' => 'Descripción', 'attr' => array('class' => 'form-control')))        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TipoCheque::class,
        ]);
    }
}

src/Controller/TipoChequeController.php
<?php

namespace App\Controller;

use App\Entity\TipoCheque;
use App\Form\TipoChequeType;
use App\Repository\TipoChequeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Knp\Component\Pager\PaginatorInterface;

/**
 * @Route("/tipocheque")
 */
class TipoChequeController extends AbstractController {

    /**
     * @Route("/operator/", name="tipocheque_index", methods={"GET"})
     */
    public function index(Request $request, TipoChequeRepository $tipochequeRepository, PaginatorInterface $paginator): Response {
        $filtros = $request->query->all();
        $tipocheques = $paginator->paginate(
                $tipochequeRepository->filter($filtros),
                $request->query->getInt('page', 1),
                15
        );
        return $this->render('tipocheque/index.html.twig', [
                    'tipocheques' => $tipocheques,
        ]);
    }

    /**
     * @Route("/admin/new", name="tipocheque_new", methods={"GET","POST"})
     */
    public function new(Request $request, TranslatorInterface $translator): Response {
        $tipocheque = new TipoCheque();
        $form = $this->createForm(TipoChequeType::class, $tipocheque);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($tipocheque);
            $entityManager->flush();
            $this->addFlash('msgOk', $translator->trans('Check type created successfully.'));
            return $this->redirectToRoute('tipocheque_index');
        }
        if ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('msgError', $translator->trans('It was not possible to create the check type.'));
        }
        return $this->render('tipocheque/new.html.twig', [
                    'tipocheque' => $tipocheque,
                    'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/activate/{id}", name="tipocheque_activate", methods={"GET"})
     *
     */
    public function activateAction(Request $request, TipoCheque $tipocheque, TranslatorInterface $translator) {
        if (!$tipocheque) {
            $this->addFlash('msgOk', $translator->trans('It was not possible to change the status of the selected check type.'));
        } else {
            $activo = $request->get('activo');
            $entityManager = $this->getDoctrine()->getManager();
            $tipocheque->setActivo($activo);
            $entityManager->persist($tipocheque);
            $entityManager->flush();
            $this->addFlash('msgOk', $translator->trans('Check type status has been changed', ['%check type%' => $tipocheque->getDescripcion()]));
        }
        return $this->redirect($this->generateUrl('tipocheque_index'));
    }

    /**
     * @Route("/admin/{id}/edit", name="tipocheque_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TipoCheque $tipocheque, TranslatorInterface $translator): Response {
        $form = $this->createForm(TipoChequeType::class, $tipocheque);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('msgOk', $translator->trans('Check type edited successfully.'));
            return $this->redirectToRoute('tipocheque_index');
        }
        if ($form->isSubmitted() && !$form->isValid()) {
            $this->addFlash('msgError', $translator->trans('It was not possible to edit the check type.'));
        }
        return $this->render('tipocheque/edit.html.twig', [
                    'tipocheque' => $tipocheque,
                    'form' => $form->createView(),
        ]);
    }

}

templates/tipocheque/_form.html.twig
{{ form_start(form) }}
<!-- /.card-header -->
<div class="card-body">  
    <div class="row">
        <div class="col-md-6">
            <strong>{{ 'Description'|trans }}</strong><br>
            {{ form_widget(form.descripcion) }}
            {{ form_errors(form.descripcion) }}
        </div>
    </div>
    <button class="btn btn-info float-left mt-2 mb-2 mr-2" type="submit" >{{ 'Save'|trans }}</button>
</div>
{{ form_end(form) }}

templates/tipocheque/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Check types' | trans }}{% endblock %}

{% block body %}
    <h4>{{'Check types'|trans}}</h4>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ path('tipocheque_index') }}" class="btn btn-sm btn-primary float-right">{{ "Go to list" | trans }}</a>
                    <a onclick="goBack();" class="btn btn-sm btn-info float-right" style="margin-right: 1rem;">{{ "Back" | trans }}</a>
                    <h5 >
                        <strong> {{ 'Edit check type'|trans }}</strong>
                    </h5>

                </div>
                {{ include('tipocheque/_form.html.twig') }}   
            </div>
        </div>
    </div>
{% endblock %}

templates/tipocheque/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% include('tipocheque/seeker.html.twig' ) %}
    <br>
    <div class="card shadow mb-4">
        <div class="card-header">           
            {% if is_granted('ROLE_ADMIN') %}             
            <a class="btn btn-sm btn-primary col-xs-3 float-right " href="{{ path('tipocheque_new') }}">{{'Create'|trans}}</a>
            {% endif %}
            <h6 class="font-weight-bold text-primary col-xs-3" >{{'Bank List'|trans}}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">               
                <table  class="table table-bordered" data-toggle="table"  data-show-columns="true" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-sortable="true">{{ 'Id'|trans }} </th>
                            <th data-sortable="true">{{ 'Description'|trans }}</th>                            
                            <th data-sortable="true">{{ 'Status'|trans }}</th>   
                            {% if is_granted('ROLE_ADMIN') %}                                        
                            <th>{{'Actions'|trans}}</th>
                            {% endif %}
                        </tr>
                    </thead>
                    <tbody>                        
                        {% if tipocheques|length > 0 %}
                            {% for tipocheque in tipocheques %}
                                <tr>
                                    <td>{{ tipocheque.id }}</td>
                                    <td>{{ tipocheque.descripcion }}</td>
                                    
                                    <td>{{ tipocheque.activoString|trans }}</td>                                   
                                    {% if is_granted('ROLE_ADMIN') %}                                        
                                    <td>                                                                            
                                        <a  class="mr-2" href="{{ path('tipocheque_edit', {'id': tipocheque.id}) }}" title="{{ 'Edit'|trans }}">
                                            <i class="fas fa-edit text-primary"></i>
                                        </a>                                          
                                        {% if tipocheque.activo %}                                        
                                            <a  href="{{ path('tipocheque_activate', { 'id': tipocheque.id,'activo': '0' }) }}"  title="{{ 'Inactivate'|trans }}" >
                                                <i class="fa fa-times text-danger mr-2"></i>
                                            </a>
                                        {% endif %}
                                        {% if  not tipocheque.activo %}
                                            <a href="{{ path('tipocheque_activate', { 'id': tipocheque.id,'activo':'1' }) }}"  title="{{ 'Activate'|trans }}" >
                                                <i class="fa fa-undo text-warning"></i>
                                            </a>
                                        {% endif %}
                                    </td>
                                     {% endif %}
                                </tr>                        
                            {% endfor %}
                        {% else %}
                            <tr>                               
                                <th >{{'No records found'|trans}}</th>                                
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
                <div class="navigation">
                    {{ knp_pagination_render(tipocheques) }}
                </div>
            </div>
        </div>
    </div>     
{% endblock %}
{% block pagescripts %}
    <script type="text/javascript">

    </script>
{% endblock %}

templates/tipocheque/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h4>{{'Check types'|trans}}</h4>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ path('tipocheque_index') }}" class="btn btn-sm btn-primary float-right">{{ "Go to list" | trans }}</a>
                    <a onclick="goBack();" class="btn btn-sm btn-info float-right" style="margin-right: 1rem;">{{ "Back" | trans }}</a>
                    <h5 >
                        <strong> {{ 'New check type'|trans }}</strong>
                    </h5>

                </div>
                {{ include('tipocheque/_form.html.twig') }}   
            </div>
        </div>
    </div>
{% endblock %}

templates/tipocheque/seeker.html.twig
<div class="filters-content">
    <div class="card">
        <div class="card-header">
            <div class="btn-group btn-group-toggle col-xs-6 " data-toggle="buttons">
                <label class="btn btn-info btn-sm active showFilters " data-option="1">
                    <input  type="radio" name="options" id="option1" autocomplete="off" checked> {{ 'Hide filters' | trans }}
                </label>
                <label class="btn btn-info btn-sm showFilters"  data-option="2">
                    <input type="radio" name="options" id="option2" autocomplete="off">{{ 'Show filters' | trans }}
                </label>
            </div>
        </div>
        <div class="card-body" id="seekerFilters">
            <form class="col-xs-12" method="get" action="{{ path('tipocheque_index') }}"  >

                <div class="row">
                    <!--Filter by Code / Description -->
                    <div class="col-sm-4">
                        <div class="form-group col-xs-12">
                            <label for="finder">
                                {{ 'Description' | trans }} 
                            </label>
                            <div class="input-group">  
                                <input type="text" value="{{ app.request.query.get('descripcion')}}" name="descripcion" class="form-control"/>
                            </div>
                        </div>
                    </div>      
                    <div class="col-sm-4">
                        <div class="form-group col-xs-12">
                            <label for="estado">
                                {{ 'Status' | trans }} 
                            </label>
                            <div class="input-group">                                                                                             
                                {{ DefaultService.getStatusSelect() }}                                                       
                            </div>
                        </div>
                    </div>                   
                </div>
                <div class="row">
                    <a class="btn btn-success btn-sm ml-3" href="?reset">
                        <i class="fa fa-times"></i> {{ 'Clean' | trans | capitalize }}
                    </a>
                    <button class="btn btn-primary btn-sm" type="submit" style="margin-left:1rem;">
                        {{ 'Filter' | trans | capitalize }}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>   
<script>
    $(function () {
        var activo = '{{ app.request.query.get('activo')}}';
        $('#activo').val(activo).change();
    });
</script>

templates/tipocheque/select.html.twig
<select {% if array==1 %} id="tipoCheque[]" {% else %}id="tipoCheque"{% endif %} {% if array==1 %} name="tipoCheque[]" {% else %}name="tipoCheque"{% endif %}  class="form-control select2" >
    <option value="">{{ 'Select check type'|trans}}</option>
    {% for tipoCheque in tipoCheques %}                            
        <option value="{{tipoCheque.id}}" >{{tipoCheque.descripcion}}</option>                            
    {% endfor %}
</select>