src/Entity/Factura.php
<?php

namespace App\Entity;

use App\FacturaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Common\Moneda;

/**
 * @ORM\Entity(repositoryClass=App\Repository\FacturaRepository::class)
 * @ORM\Table(name="factura")
 */
class Factura extends Moneda {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\OneToOne(targetEntity="MovimientoCC")
     * @ORM\JoinColumn(name="movimientocc_id", referencedColumnName="id", nullable=false)
     * */
    private $movimientocc;

    /**
     * @ORM\ManyToOne(targetEntity="ListaPrecio")
     * @ORM\JoinColumn(name="listaPrecio_id", referencedColumnName="id")
     */
    protected $listaPrecio;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    protected $descuento = 0;

    /**
     * @ORM\Column(type="float", nullable=false)
     */
    protected $bonificacion = 0;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    protected $observacion;

    /**
     * @ORM\OneToMany(targetEntity="ProductoFactura", mappedBy="factura", cascade={"persist", "remove"} )
     */
    protected $productosFactura;

    /*     * ********************************
     * __construct
     *
     * 
     * ******************************** */

    public function __construct() {
        $this->productosFactura = new ArrayCollection();
    }

    /*     * ********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     * ******************************* */

    public function __toString() {
        return 'Factura Nro. ' . $this->id;
    }


    public function getTotal() {
        $total = round($this->getSubtotal() -  $this->getDescuentoValue() - $this->bonificacion, 2);
        return $total;
    }

    public function getDescuentoValue() {
        return $this->getSubtotal() * $this->descuento / 100;
    }

    public function getSubtotal() {
        $subTotal = 0;
        foreach ($this->productosFactura as $productoFactura) {
            $subTotal = $subTotal + $productoFactura->getImporte();
        }
        return $subTotal;
    }

    public function getId(): ?int {
        return $this->id;
    }


    public function getDescuento(): ?float {
        return $this->descuento;
    }

    public function setDescuento(float $descuento): self {
        $this->descuento = $descuento;

        return $this;
    }

    public function getBonificacion(): ?float {
        return $this->bonificacion;
    }

    public function setBonificacion(float $bonificacion): self {
        $this->bonificacion = $bonificacion;

        return $this;
    }

    public function getObservacion(): ?string {
        return $this->observacion;
    }

    public function setObservacion(?string $observacion): self {
        $this->observacion = $observacion;

        return $this;
    }

    public function getMovimientocc(): ?MovimientoCC {
        return $this->movimientocc;
    }

    public function setMovimientocc(?MovimientoCC $movimientocc): self {
        $this->movimientocc = $movimientocc;

        return $this;
    }

    public function getListaPrecio(): ?ListaPrecio {
        return $this->listaPrecio;
    }

    public function setListaPrecio(?ListaPrecio $listaPrecio): self {
        $this->listaPrecio = $listaPrecio;

        return $this;
    }

    /**
     * @return Collection|ProductoFactura[]
     */
    public function getProductosFactura(): Collection {
        return $this->productosFactura;
    }

    public function addProductosFactura(ProductoFactura $productosFactura): self {
        if (!$this->productosFactura->contains($productosFactura)) {
            $this->productosFactura[] = $productosFactura;
            $productosFactura->setFactura($this);
        }

        return $this;
    }

    public function removeProductosFactura(ProductoFactura $productosFactura): self {
        if ($this->productosFactura->contains($productosFactura)) {
            $this->productosFactura->removeElement($productosFactura);
            // set the owning side to null (unless already changed)
            if ($productosFactura->getFactura() === $this) {
                $productosFactura->setFactura(null);
            }
        }

        return $this;
    }

}

src/Entity/Producto.php
<?php

namespace App\Entity;

use App\Entity\Tienda\Cupon;
use App\Entity\Tienda\DetallePedido;
use App\Entity\Tienda\Menu;
use App\Entity\Tienda\ProductoGrupo;
use App\Entity\Common\Common;
use App\Entity\Tienda\ProductoLinea;
use App\Entity\Tienda\ProductosLineaProducto;
use App\Entity\Tienda\Promotion;
use App\ProductoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=App\Repository\ProductoRepository::class)
 * @ORM\Table(name="producto")
 */
class Producto extends Common {

    const VISIBLE = 'Visible on the web';
    const NO_VISIBLE = 'No visible on the web';
    const NOVEDAD = 'It is a novelty';
    const NO_NOVEDAD = 'It is not a novelty';
    const DESTACADO = 'It is a standout';
    const NO_DESTACADO = 'It is not a standout';
    const PESOS = '$';
    const DOLAR = 'u$s';
    const COD_PESOS = '1';
    const COD_DOLAR = '2';
    const UNIDAD = 'Unidades';
    const GRAMO_PLATA = 'Gramos de plata';
    const GRAMO_ORO = 'Gramos de oro';
    const COD_UNIDAD = 'U';
    const COD_GRAMO_PLATA = 'P';
    const COD_GRAMO_ORO = 'O';
    const GRABABLE = 'It is recordable';
    const NO_GRABABLE = 'It is not recordable';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)    
     */
    protected $descripcionampliada;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(
     *       message = "Debe agregar una descripción."
     *              )
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="string", length=25,nullable=true)
     */
    protected $descripcionMenu;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(
     *       message = "Debe indicar el stock."
     *              )
     */
    protected $stock;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $plata = 0;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $oro = 0;

    /**
     * @ORM\Column(type="string", length=3)
     */
    protected $moneda;

    /**
     * @ORM\Column(type="float", nullable=false)
     * @Assert\NotBlank(
     *       message = "Debe agregar un costo."
     *              )
     */
    protected $costo;

    /**
     * @ORM\Column(type="string", length=50,  unique=true)
     */
    protected $codigo;

    /**
     * @ORM\ManyToOne(targetEntity="Categoriasubcategoria", inversedBy="productos")
     * @ORM\JoinColumn(name="categoriasubcategoria_id", referencedColumnName="id")     
     */
    protected $categoriasubcategoria;

    /**
     * @ORM\OneToMany(targetEntity="Precio", mappedBy="producto", cascade={"persist", "remove"})
     */
    protected $precios;

    /**
     * @ORM\OneToMany(targetEntity="ProductoFactura", mappedBy="producto")
     */
    protected $productosFactura;

    /**
     * @ORM\OneToMany(targetEntity="ImagenProducto", mappedBy="producto", cascade={"persist", "remove"})
     * @ORM\OrderBy({"pos" = "ASC"})
     */
    protected $imagenesproducto;

    /**
     * @ORM\OneToMany(targetEntity="ProductoConsignacion", mappedBy="producto", cascade={"remove"})     
     */
    protected $productosConsignacion;

    /**
     * @ORM\Column(type="string", length=1)
     */
    protected $tipoStock = 'U'; //Valores Posibles U O P

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Assert\NotNull(message = "El campo no puede estar en blanco.")
     * @Assert\Choice(choices = {true, false}, message = "Elija un valor.")
     */
    protected $visible = true;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Assert\Choice(choices = {true, false}, message = "Elija un valor.")
     */
    protected $novedad = false;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Assert\Choice(choices = {true, false}, message = "Elija un valor.")
     */
    protected $destacado = false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $descuento = 0;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $orden = 100000;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Assert\Choice(choices = {true, false}, message = "Elija un valor.")
     */
    protected $esGrabable = false;

    /**
     * @ORM\Column(type="float", nullable=false, options={"default" : 0})
     */
    protected $maxGrabado = 0;

    /**
     * @ORM\Column(type="string", length=50,nullable=true)   
     */
    protected $tipoMedida;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\ProductosLineaProducto", mappedBy="producto")
     */
    protected $productosLineaProducto;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\ProductoGrupo", mappedBy="producto")
     */
    protected $productosGrupo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\Menu", mappedBy="producto1")
     */
    protected $menu1;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\Menu", mappedBy="producto2")
     */
    protected $menu2;

    /**
     * @ORM\OneToMany(targetEntity="AtributosProducto", mappedBy="producto")
     */
    protected $atributosProducto;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\DetallePedido", mappedBy="producto")
     */
    protected $detallespedido;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\Promotion", mappedBy="producto")
     */
    protected $promotions;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\Cupon", mappedBy="producto")
     */
    protected $cupones;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Tienda\ProductoLinea", mappedBy="producto")
     */
    protected $productosLinea;

    /*     * ********************************
     * __construct
     *
     * 
     * ******************************** */

    public function __construct() {
        $this->precios = new ArrayCollection();
        $this->productosFactura = new ArrayCollection();
        $this->imagenesproducto = new ArrayCollection();
        $this->productosConsignacion = new ArrayCollection();
        $this->productosGrupo = new ArrayCollection();
        $this->productosLineaProducto = new ArrayCollection();
        $this->productosLinea = new ArrayCollection();
        $this->promotions = new ArrayCollection();
        $this->menu1 = new ArrayCollection();
        $this->menu2 = new ArrayCollection();
        $this->atributosProducto = new ArrayCollection();
        $this->detallespedido = new ArrayCollection();
        $this->cupones = new ArrayCollection();
    }

    /*     * ********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     * ******************************* */

    public function __toString() {
        return $this->getCodigo() . ' - ' . $this->getDescripcion();
    }

    public function getTitleMenu() {
        return (is_null($this->descripcionMenu)) ? $this->codigo : $this->descripcionMenu;
    }

    public function hasImages() {
        foreach ($this->imagenesproducto as $imagenProducto) {
            if ($imagenProducto->getEnabled() == TRUE) {
                return true;
            }
        }
        return false;
    }

    /*
     * Has images by product
     */

    public function hasPrice($listaPrecioId) {
        foreach ($this->precios as $precio) {
            if ($precio->getActivo() == TRUE && $precio->getListaPrecio()->getId() == $listaPrecioId) {
                return true;
            }
        }
        return false;
    }

    public function getPrecio($listaPrecioId) {
        foreach ($this->precios as $precio) {
            if ($precio->getActivo() == TRUE && $precio->getListaPrecio()->getId() == $listaPrecioId) {
                return $precio->getValor();
            }
        }
        return '';
    }

    /**
     * Get moneda
     *
     * @return string 
     */
    public function getMonedaSimbolo() {
        if ($this->moneda == self::COD_PESOS) {
            return self::PESOS;
        }

        if ($this->moneda == self::COD_DOLAR) {
            return self::DOLAR;
        }
    }

    public function getTipoStockString() {
        switch ($this->getTipoStock()) {
            case self::COD_UNIDAD:
                return self::UNIDAD;
            case self::COD_GRAMO_PLATA:
                return self::GRAMO_PLATA;
            case self::COD_GRAMO_ORO:
                return self::GRAMO_ORO;
            default:
                return '';
        }
    }

    public function getVisibleString() {
        if ($this->visible) {
            return self::VISIBLE;
        }
        return self::NO_VISIBLE;
    }

    public function getDestacadoString() {
        if ($this->destacado) {
            return self::DESTACADO;
        }
        return self::NO_DESTACADO;
    }

    public function getNovedadString() {
        if ($this->novedad) {
            return self::NOVEDAD;
        }
        return self::NO_NOVEDAD;
    }

    public function getEsGrabableString() {
        if ($this->esGrabable) {
            return self::GRABABLE;
        }
        return self::NO_GRABABLE;
    }

    public function getId(): ?int {
        return $this->id;
    }

    public function getDescripcionampliada(): ?string {
        return $this->descripcionampliada;
    }

    public function setDescripcionampliada(?string $descripcionampliada): self {
        $this->descripcionampliada = $descripcionampliada;

        return $this;
    }

    public function getDescripcion(): ?string {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): self {
        $this->descripcion = $descripcion;

        return $this;
    }

templates/facturaproveedorgastos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'Banks' | trans }}{% endblock %}

{% block body %}
    <h4>{{'Banks'|trans}}</h4>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ path('banco_index') }}" class="btn btn-sm btn-primary float-right">{{ "Go to list" | trans }}</a>
                    <a onclick="goBack();" class="btn btn-sm btn-info float-right" style="margin-right: 1rem;">{{ "Back" | trans }}</a>
                    <h5 >
                        <strong> {{ 'Edit Bank'|trans }}</strong>
                    </h5>

                </div>
                {{ include('banco/_form.html.twig') }}   
            </div>
        </div>
    </div>
{% endblock %}

templates/facturaproveedorgastos/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% include('facturaproveedorgastos/seeker.html.twig' ) %}
    <br>
    <div class="card shadow mb-4">
        <div class="card-header">           
            {% if is_granted('ROLE_ADMIN') %}             
                <a class="btn btn-sm btn-primary col-xs-3 float-right " href="{{ path('facturaproveedor_gastos_new') }}">{{'Create'|trans}}</a>
                <a class="btn btn-sm btn-secondary col-xs-3 float-right mr-2 btn-excel" href=""><i class="far fa-file-excel mr-1"></i><span>{{'Export'|trans}}</span></a>
            {% endif %}
            <h6 class="font-weight-bold text-primary col-xs-3" >{{'Invoices Provider Expenses List'|trans}}</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">               
                <table  class="table table-bordered" data-toggle="table"  data-show-columns="true" cellspacing="0">
                    <thead>
                        <tr>
                            <th data-sortable="true">{{ 'Expense Type'|trans }} </th>
                            <th data-sortable="true">{{ 'Registration Date'|trans }} </th>
                            <th data-sortable="true">{{ 'Date'|trans }} </th>                            
                            <th data-sortable="true">{{ 'Number'|trans }}</th> 
                            <th data-sortable="true">{{ 'Provider'|trans }}</th> 
                            <th data-sortable="true">{{ 'Gold'|trans }}</th>   
                            <th data-sortable="true">{{ 'Silver'|trans }}</th>   
                            <th data-sortable="true">{{ 'Amount'|trans }}</th>   
                        </tr>
                    </thead>
                    <tbody>                        
                        {% if facturasproveedor|length > 0 %}
                            {% for facturaproveedor in facturasproveedor %}
                                <tr>
                                    <td>{{ facturaproveedor.tipoGasto }}</td>
                                    <td>{{ facturaproveedor.created|date('Y-m-d') }}</td>
                                    <td>{{ facturaproveedor.fecha|date('Y-m-d') }}</td>
                                    <td>
                                        <a href="{{ path('facturaproveedor_gastos_show',{'id':facturaproveedor.id}) }}">
                                            {{ facturaproveedor}}
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ path('movimientocc_index', {'id': facturaproveedor.movimientocc.clienteProveedor.id}) }}" title="{{ 'Go to current account'|trans }}">
                                        {{ facturaproveedor.movimientocc.clienteProveedor}}
                                        </a>
                                    </td>                                    
                                    <td>{{ facturaproveedor.oro}} gr</td>                                   
                                    <td>{{ facturaproveedor.plata}} gr</td>                                   
                                    <td>{{facturaproveedor.monedaSimbolo}} {{ facturaproveedor.importe}}</td>                                   
                                </tr>                        
                            {% endfor %}
                        {% else %}
                            <tr>                               
                                <th >{{'No records found'|trans}}</th>                                
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
                <div class="navigation">
                    {{ knp_pagination_render(facturasproveedor) }}
                </div>
            </div>
        </div>
    </div>     
{% endblock %}
{% block pagescripts %}
    <script type="text/javascript">
        $(document).ready(function(){
            $('#action').val('');
            
            $('.btn-excel').click(function(){
                event.preventDefault();
                $('#action').val('excel');
                $('form').submit();
            });
            
            $('.btn-excel').blur(function () {
                window.location.reload();
            });
        });
    </script>
{% endblock %}

templates/facturaproveedorgastos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ facturaproveedor }}
{% endblock %}

{% block body %}
    <h4>{{ facturaproveedor}}</h4>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a href="{{ path('facturaproveedor_index') }}" class="btn btn-sm btn-primary float-right">{{ "Go to list" | trans }}</a>
                    <a onclick="goBack();" class="btn btn-sm btn-info float-right mr-2" >{{ "Back" | trans }}</a>                    
                </div>              

                <div class="card-body">  
                    <div class="row">
                        <!--Provider --> 
                        <div class="col-sm-6">
                            <div class="form-group col-xs-12">
                                <strong>{{ 'Provider' | trans }}:</strong>                                 
                                {{ facturaproveedor.movimientocc.clienteProveedor }}                                                                
                            </div>
                        </div>                               
                        <!--Date -->        
                        <div class="col-sm-6">
                            <strong>{{ 'Date'|trans }}:</strong>
                            {{ facturaproveedor.fecha|date('d-m-Y') }}                       
                        </div>                                
                    </div>                    

                    <div class="row">
                        <!--Registration Date -->        
                        <div class="col-sm-6">
                            <strong>{{ 'Registration Date'|trans }}:</strong>
                            {{ facturaproveedor.created|date('d-m-Y') }}                       
                        </div>                                

                    </div>

                    <!--Totals -->        
                    <div class="row">

                        <div class="col-md-6 mt-2">
                            <div class="row">       
                                <div class="col-6 text-right">
                                    <strong>{{'Sub Total'|trans}}:</strong>
                                </div>
                                <div class="col-6 text-center" id="divSubtotal"> 
                                    {{facturaproveedor.monedaSimbolo}} {{ facturaproveedor.importe }}                                    
                                </div>
                            </div>
                            <div class="row">        
                                <div class="col-6 text-right">
                                    <strong>{{'Discount'|trans}}<span id="valueDiscount">({{ facturaproveedor.descuento}} %)</span>:</strong>
                                </div>
                                <div class="col-6 text-center" id="divDiscount"> 
                                    {{facturaproveedor.monedaSimbolo}} {{ facturaproveedor.descuentoValue }}    
                                </div>
                            </div>
                            <div class="row">        
                                <div class="col-6 text-right">
                                    <strong>{{'Bonification'|trans}}<span id="valueBonification">(-)</span>:</strong>
                                </div>
                                <div class="col-6 text-center" id="divBonification">
                                    {{facturaproveedor.monedaSimbolo}} {{ facturaproveedor.bonificacion }}    
                                </div>
                            </div>
                            <div class="row">        
                                <div class="col-6 text-right">
                                    <strong>{{'Total'|trans}}:</strong>
                                </div>
                                <div class="col-6 text-center" id="divTotal">
                                    {{facturaproveedor.monedaSimbolo}} {{ facturaproveedor.total }}    
                                </div>
                            </div>
                        </div>
                        {% if facturaproveedor.oro >0 or  facturaproveedor.plata >0 %}
                            <div class="col-md-6">
                                {% if facturaproveedor.plata >0 %}
                                    <div class="row">       
                                        <div class="col-6 text-right">
                                            <strong>{{'Silver Total'|trans}}:</strong>
                                        </div>
                                        <div class="col-6 text-center" > 
                                            {{ facturaproveedor.plata }} gr                                    
                                        </div>
                                    </div>
                                {% endif %}
                                {% if facturaproveedor.oro >0 %}
                                    <div class="row">       
                                        <div class="col-6 text-right">
                                            <strong>{{'Gold Total'|trans}}:</strong>
                                        </div>
                                        <div class="col-6 text-center" > 
                                            {{ facturaproveedor.oro }} gr                                    
                                        </div>
                                    </div>
                                {% endif %}
                            </div>
                        {% endif %}
                    </div>
                    <!--Observation -->        
                    <div class="row mt-2">
                        <div class="col-md-6">
                            <strong>{{ 'Observation'|trans }}</strong><br>
                            {{ facturaproveedor.observacion}}
                        </div>                            
                    </div>    
                </div>                
            </div>
        </div>
    </div>
    <div class="container" >
        <div class="row mt-2" >
            <div class="card col-12">
                <div class="card-header">
                    <div class="row" >
                        <div class="col-6 text-center" >
                            <a class="btn btn-info" href="{{ path('ordenpago_new', { 'facturaproveedorId': facturaproveedor.id})}}">
                                <i class="fas fa-hands-helping"></i> {{'Pay'|trans}}
                            </a>
                        </div>
                        <div class="col-6 text-center">
                            <a class="btn btn-info" href="{{ path('movimientocc_index', {'id': facturaproveedor.movimientocc.clienteProveedor.id})}}">                           
                                <i class="fas fa-book-open"> </i> {{'Current account'|trans}}
                            </a>
                        </div>
                        {#<div class="col-4 text-center">
                            <a class="btn btn-info" id="print">
                                <i class="fas fa-print"></i> {{'Print'|trans}}
                            </a>
                        </div>
                        #}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#<script type="text/javascript" src="{{ asset('js/jspdf/jspdf.min.js') }}"></script>
    <script language="Javascript">
        $(function () {
            $('#print').click(function () {
                print();
            });
        });
        function print() {
            var doc = new jsPDF();

            doc.setFontSize(12);

            doc.line(10, 5, 198, 5);
            doc.text(25, 10, '{{factura}}');

            doc.setFontSize(10);
            doc.text(25, 13, '{{ 'Customer' | trans }}: {{ factura.movimientocc.clienteProveedor }}');
            doc.text(140, 13, '{{ 'Date' | trans }}: {{ factura.fecha|date('Y-m-d H:i:s') }}');

            doc.line(10, 16, 198, 16);

            doc.text(18, 25, '{{ 'Quantity' | trans }}');
            doc.text(48, 25, '{{ 'Code' | trans }}');
            doc.text(85, 25, '{{ 'Description' | trans }}');
            doc.text(130, 25, '{{ 'Price' | trans }}');
            doc.text(176, 25, '{{ 'SubTotal' | trans }}');

        {% set cont = 0 %}								
        {% set alto = 35 %}				
        {% for productoFactura in factura.productosFactura %}
                doc.setFontSize(8);
                        doc.line(10, {{ alto - 3 }}, 198, {{ alto - 3 }});
                        doc.text(23, {{ alto }}, '{{ productoFactura.cantidad }}');
            {% if productoFactura.producto %}
                    doc.text(44, {{ alto }}, '{{ productoFactura.producto.codigo }}');
            {% else %}
                    doc.text(44, {{ alto }}, '000');
            {% endif %}
            {% if productoFactura.descripcion|length > 32 %}
                    doc.text(74, {{ alto }}, '{{ productoFactura.descripcion[0:30] }}...');
            {% else %}
                    doc.text(74, {{ alto }}, '{{ productoFactura.descripcion }}');
            {% endif %}
                    doc.text(130, {{ alto }}, '{{ factura.listaPrecio.monedaSimbolo }} {{ productoFactura.precio }}');
                            doc.text(170, {{ alto }}, '{{ factura.listaPrecio.monedaSimbolo }} {{ productoFactura.importe }}');

            {% set alto = alto + 4 %}								

            {% if  cont > 50 %}
                    doc.addPage();
                {% set alto = 25 %}								
                    doc.text(18, {{ alto }}, '{{ 'Quantity' | trans }}');
                            doc.text(48, {{ alto }}, '{{ 'Code' | trans }}');
                            doc.text(85, {{ alto }}, '{{ 'Description' | trans }}');
                            doc.text(130, {{ alto }}, '{{ 'Price' | trans }}');
                            doc.text(176, {{ alto }}, '{{ 'SubTotal' | trans }}');
                {% set alto = 35 %}
                {% set cont = 0 %}								
            {% endif %}
            {% set cont = cont +1 %}								
        {% endfor %}
                doc.line(10, {{ alto - 3 }}, 198, {{ alto - 3}});

                doc.setFontSize(10);

                doc.line(170, {{ alto + 20 }}, 190, {{ alto +20 }});
                        doc.text(130, {{ alto + 30 }}, 'Sub Total');
                        doc.text(170, {{ alto + 30 }}, '{{ factura.listaPrecio.monedaSimbolo }} {{ factura.subtotal }}');

                doc.text(130, {{ alto + 40 }}, 'Descuento %{{ factura.descuento }}');
                        doc.text(170, {{ alto + 40 }}, '{{ factura.listaPrecio.monedaSimbolo }} {{ factura.descuentoValue }}');

                doc.text(130, {{ alto + 50 }}, 'Bonificación');
                        doc.text(170, {{ alto + 50 }}, '{{ factura.listaPrecio.monedaSimbolo }} {{ factura.bonificacion }}');

                doc.text(130, {{ alto + 60 }}, 'TOTAL');
                        doc.text(170, {{ alto + 60 }}, '{{factura.listaPrecio.monedaSimbolo }} {{ factura.importe }}');
        {% if factura.oro is defined and factura.oro >0%}
                doc.text(15, {{ alto + 70 }}, 'Total Au');
                        doc.text(30, {{ alto + 70 }}, '{{ factura.oro|default('--') }} gr');
        {% endif %}
        {% if factura.plata is defined and factura.plata >0%}
                doc.text(70, {{ alto + 70 }}, 'Total Ag');
                        doc.text(90, {{ alto + 70 }}, '{{ factura.plata|default('--') }} gr');
        {% endif %}
        {% if factura.observaciones is defined and factura.observaciones !=''%}
                doc.text(18, {{ alto + 80 }}, 'Observaciones');
                        doc.text(18, {{ alto + 90 }}, '{{ factura.observaciones|default('Without observations'|trans) }}');
        {% endif %}
                doc.save('{{factura}}.pdf');
            }
    </script> #}
{% endblock %}